// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjDcmEcfA6jQYMfsxR3d-hiSVT3VA2pMk',
    appId: '1:784154724919:web:5656b913f8b771e3b0cdb2',
    messagingSenderId: '784154724919',
    projectId: 'hairconnect-70b13',
    authDomain: 'hairconnect-70b13.firebaseapp.com',
    storageBucket: 'hairconnect-70b13.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZLywZobMPeA1T2HGqHWwXG4EiLa1f9L4',
    appId: '1:784154724919:android:cfca133c406d6e14b0cdb2',
    messagingSenderId: '784154724919',
    projectId: 'hairconnect-70b13',
    storageBucket: 'hairconnect-70b13.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaPMfzwhrn9fJs0ArAm0EM6tjrzrr9JFM',
    appId: '1:784154724919:ios:2d9b2f28cd322c62b0cdb2',
    messagingSenderId: '784154724919',
    projectId: 'hairconnect-70b13',
    storageBucket: 'hairconnect-70b13.firebasestorage.app',
    iosBundleId: 'com.example.hairConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaPMfzwhrn9fJs0ArAm0EM6tjrzrr9JFM',
    appId: '1:784154724919:ios:2d9b2f28cd322c62b0cdb2',
    messagingSenderId: '784154724919',
    projectId: 'hairconnect-70b13',
    storageBucket: 'hairconnect-70b13.firebasestorage.app',
    iosBundleId: 'com.example.hairConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjDcmEcfA6jQYMfsxR3d-hiSVT3VA2pMk',
    appId: '1:784154724919:web:6be912f5c55d1655b0cdb2',
    messagingSenderId: '784154724919',
    projectId: 'hairconnect-70b13',
    authDomain: 'hairconnect-70b13.firebaseapp.com',
    storageBucket: 'hairconnect-70b13.firebasestorage.app',
  );
}
